apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-api-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:

  rules:
  - host: "dev.simple-api.192.168.0.66.sslip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-api-svc
            port:
              number: 8080
  