apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-api-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: simple-api
  namespaceSelector:
    # any: true
    matchNames:
      - api
  endpoints:
    - port: http-svc
      path: "/actuator/prometheus"