apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-api-configmap
  namespace: api
  
data:
  JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/elastic-apm-agent-1.33.0.jar -Delastic.apm.service_name=simple-api -Delastic.apm.server_urls=http://elastic-apm-apm-server.elastic-apm.svc:8200 -Delastic.apm.secret_token=d3dc31c5db912b297835f934292218c2af5ea7ba -Delastic.apm.environment=production -Delastic.apm.application_packages=com.example"
  