##########local########
GET http://localhost:9320/api/hello

###
GET http://localhost:9320/api/simple

###
GET http://localhost:9320/api/version




##### cache ############
GET http://localhost:9320/localCache/details

GET http://localhost:9320/localCache/status

POST http://localhost:9320/localCache/clearAll

POST http://localhost:9320/localCache/clear?cacheName=commonCache