######## 
# Deployment
#########

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - name: simple
          image: asia.gcr.io/io203-101/simple:2.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8088

