apiVersion: skaffold/v4beta1
kind: Config

profiles:
  - name: dev
    build:
      local:
        push: false
      artifacts:
        - image: saturn203/simple-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"           
            fromImage: eclipse-temurin:17.0.2_8-jre
          hooks:
            after:
              - command: ["sh", "-c", "./hook.sh"]
                os: [darwin, linux]
             
            
   
    manifests:
      kustomize:
        paths:      
        - k8s/dev/kustomization.yaml
        
    
    portForward:
    - resourceType: deployment
      resourceName: simple-api-deploy
      namespace: api
      port: 8080
      localPort: 9320 # *Optional*   
     
 