apiVersion: skaffold/v4beta1
kind: Config

profiles:
  - name: dev
    build:
      local:
        push: true
        useDockerCLI: true
      artifacts:
        - image: saturn203/simple-api
         
    manifests:
      rawYaml:
          - k8s/dev/simple-api.yaml
          # - k8s/dev/simple-vs.yaml
          # - k8s/dev/k8s-ingress-simple-api.yaml

    portForward:
    - resourceType: deployment
      resourceName: simple-api-deploy
      namespace: api
      port: 8080
      localPort: 9320 # *Optional*          