apiVersion: skaffold/v2beta29
kind: Config

profiles:
  - name: dev
    build:
      local:
        push: true
      artifacts:
        - image: saturn203/simple-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            # fromImage: eclipse-temurin:17.0.2_8-jre
            fromImage: saturn203/jre-17-pinpoint:v1.0
    deploy:
      kubectl:
        manifests:
          - k8s/dev/simple-api.yaml
          # - k8s/dev/simple-vs.yaml
          # - k8s/dev/k8s-ingress-simple-api.yaml
          
  - name: kind
    build:
      local:
        push: false
      artifacts:
        - image: simple-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"
            fromImage: eclipse-temurin:17.0.2_8-jre
            
    deploy:
      kubectl:
        manifests:
          - k8s/kind/simple-api.yaml 

  - name: k3d
    build:
      local:
        push: false
      artifacts:
        - image: simple-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=k3d"
            fromImage: eclipse-temurin:17.0.2_8-jre
    deploy:
      kubectl:
        manifests:
          - k8s/k3d/simple-api.yaml 
          # - k8s/k3d/simple-api-ingress.yaml 
          - k8s/k3d/simple-api-ingress-traefik.yaml 

  
    # portForward:
    # - resourceType: deployment
    #   resourceName: simple-api
    #   namespace: api
    #   port: 8080
    #   localPort: 9000 # *Optional*          

  
      
