apiVersion: skaffold/v2beta18
kind: Config

profiles:
  - name: kind
    build:
      local:
        push: false
      artifacts:
        - image: simple-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"
            #  fromImage: adoptopenjdk/openjdk11
            fromImage: openjdk:11.0.11-jre-slim
    deploy:
      kubectl:
        manifests:
          - k8s/kind/*.yaml
      
  
    portForward:
    - resourceType: service
      resourceName: simple-api-svc
      namespace: api
      port: 8080
      localPort: 9320 # *Optional*          

  
      
