apiVersion: skaffold/v4beta1
kind: Config

profiles:
  - name: dev
    build:
      local:
        push: true
      artifacts:
        - image: saturn203/simple-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: eclipse-temurin:17.0.2_8-jre
    manifests:
      rawYaml:
        - k8s/dev/simple-api.yaml
    # deploy:
    #   kubectl:
    #     flags:
    #       apply:
    #         - k8s/dev/
          # - k8s/dev/simple-vs.yaml
          # - k8s/dev/k8s-ingress-simple-api.yaml
          
  - name: kind
    build:
      local:
        push: true
      artifacts:
        - image: saturn203/simple-api
          jib:
            args:
              - -Djib.dockerClient.executable=$(which podman)
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"
            fromImage: eclipse-temurin:17.0.2_8-jre
    # deploy:
    #   kubectl:
    #     flags:
    #       apply:
    #       - k8s/kind/simple-api.yaml 
    manifests:
      rawYaml:
        - k8s/kind/simple-api.yaml

  - name: k3d
    build:
      local:
        push: false
      artifacts:
        - image: simple-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=k3d"
            fromImage: eclipse-temurin:17.0.2_8-jre
    deploy:
      kubectl:
        flags:
          apply:
          - k8s/k3d/simple-api.yaml 
          # - k8s/k3d/simple-api-ingress.yaml 
          - k8s/k3d/simple-api-ingress-traefik.yaml 

  
    # portForward:
    # - resourceType: deployment
    #   resourceName: simple-api
    #   namespace: api
    #   port: 8080
    #   localPort: 9000 # *Optional*          

  
      
