apiVersion: skaffold/v2beta18
kind: Config

profiles:
  - name: dev
    build:
      local:
        push: true
      artifacts:
        - image: saturn203/simple-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            # fromImage: adoptopenjdk/openjdk11
            # fromImage: openjdk:11.0.11-jre-slim
            fromImage: eclipse-temurin:17.0.2_8-jre
    deploy:
      kubectl:
        manifests:
          - k8s/dev/*.yaml
          - k8s/dev/route/*.yaml
      

  
    # portForward:
    # - resourceType: deployment
    #   resourceName: simple-api
    #   namespace: api
    #   port: 8080
    #   localPort: 9000 # *Optional*          

  
      
