apiVersion: skaffold/v4beta1
kind: Config

profiles:
  - name: dev
    build:
      local:
        push: true
      artifacts:
        - image: saturn203/simple-api
          jib:
            args:
              - -Pdev
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            #  fromImage: adoptopenjdk/openjdk11
            fromImage: eclipse-temurin:17.0.2_8-jre
    manifests:
      rawYaml:
        - k8s/dev/simple-api.yaml
           

  
    portForward:
    - resourceType: deployment
      resourceName: simple-api-deploy
      namespace: api
      port: 8080
      localPort: 9320 # *Optional*          