##############
### local
##############

server:
  port: 9320



management:
  # endpoints.web.exposure.include: '*' # health,info,prometheus
  # metrics.distribution.percentiles-histogram.http.server.requests: true
  tracing:
    # enabled: true
    sampling.probability: 1.0

  endpoints.web.exposure.include: prometheus

# For Exemplars to work we need histogram buckets
  metrics.distribution.percentiles-histogram.http.server.requests: true

logging:
  level.org.springframework.web.servlet.DispatcherServlet: DEBUG
  pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"

