##############
### local
##############

server:
  port: 9320

spring:
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317   ## otel-collector(4317) + jaeger

