##############
### local
##############

server:
  port: 9320



management: 
  endpoints:
    web.exposure.include: prometheus # only exposure /actuator/prometheus endpoint
  metrics:
    tags:
      application: ${spring.application.name} #  필히 해주는 것이 좋다
  tracing:
    sampling.probability: 1.0


logging:
  pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"


