##############
### local
##############

server:
  port: 9320



management:
  # endpoints.web.exposure.include: '*' # health,info,prometheus
  # metrics.distribution.percentiles-histogram.http.server.requests: true
  tracing:   
    sampling.probability: 1.0
  # zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
