spring:
  profiles:
    active: local 
  application:
    name: simple-api # apply name
  devtools.restart.enabled: true
  

  config:
    import: "optional:consul:"
     
  cloud:
    consul:
     
      host: localhost
      port: 8500
     
      config:        
        enabled: true        
        prefixes: config        
        default-context: ${spring.application.name}
        profile-separator: ','       
        format: YAML
        data-key: application-config
        watch:        
          enabled: true        
          delay: 1000
     
      discovery:
        register: true                                
        instance-id: ${spring.application.name}-${random.uuid}   
        service-name: web:${spring.application.name}           
        prefer-ip-address: true                      
        ip-address: ${spring.cloud.client.ip-address}
        

        #### healthCheckPath를 설정하지 않으면 spring-actuator 를 활용한다 (spring-actuator 설치 되어 있어야 한다)        
        # healthCheckPath: /sys/healthz       

        register-health-check: true
        health-check-critical-timeout: "1m"

