##############
### local
##############

server:
  port: 9320

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.192.168.41.3.sslip.io/realms/board-service


