apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- simple-rollout.yaml
- simple-svc-active.yaml
- simple-svc-preview.yaml

images:
- name: saturn203/simple-api
  newTag: "prod-slime-v1.0"