
apiVersion: argoproj.io/v1alpha1  
kind: Rollout 

metadata:
  name: simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple
        image: saturn203/simple-api
        ports:
        - name: http
          containerPort: 8088
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
  # ----- Everything above this comment are the same as a deployment -----
    blueGreen: # A new field for the Blue Green strategy options
      previewService: simple-preview # Reference to a service
      activeService: simple-active # Reference to a service
      autoPromotionEnabled: false
      previewReplicaCount: 1
      scaleDownDelaySeconds: 60  