######### 
# Service
#########


apiVersion: v1
kind: Service
metadata:
  name: simple-preview
  labels:
    app: simple
spec:
  selector:
    app: simple
  
  ports:
  - protocol: TCP
    port: 9009
    targetPort: http
#    nodePort: 30001
#  type: LoadBalancer