
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ include "simple-api.fullname" . }}
  
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.service.port }}
    targetPort: http