apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-statestore
  namespace: api
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: host.docker.internal:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
