apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      derivedFields:
      - name: trace_id
        datasourceUid: tempo
        matcherRegex: "trace_id=(\\w+)"
        url: '$${__value.raw}'
   
